source "https://rubygems.org"

gem "neo4j", "~> 4.1.5.0.0"

gem "jruby-openssl"
gem "orm_adapter", "~> 0.0.7"
gem "pry"
gem "rake", "~> 0.9.2.2"
gem "minitest", "~> 2.12.1"
gem "guard"
gem "guard-minitest"
gem "ruby_gntp"
gem "guard-ctags-bundler"
gem "minitest-context"
