source "https://rubygems.org"

gem "neo4j", "~> 2.0.0.alpha.9"

gem "jruby-openssl"
gem "orm_adapter", "~> 0.0.7"
gem "pry"
gem "rake", "~> 0.9.2.2"
gem "minitest", "~> 2.12.1"
gem "guard"
gem "guard-minitest"
gem "m", "~> 1.1"
gem 'ruby_gntp'
