srand
$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)
require 'rubygems'
require 'bundler/setup'
require 'rake'
#require 'bundler/gem_tasks'
require 'spec/spec_helper'

require 'rake/testtask'
Rake::TestTask.new do |t|
    t.pattern = "spec/**/*_spec.rb"
end

