source :rubygems
gem "nokogiri", ">=1.5.0"
gem "fastercsv"
gem "guard"
gem "guard-minitest"
gem "pry"
gem "neo4j"
gem "minitest"


#gem "rspec"
#gem "autotest"
#gem "autotest-growl"
#gem "spork", "=0.9.0.rc4"
#gem "watchr" # might replace autotest
